/**
 * Local filesystem blob storage for session photos/videos, under
 * data/blobs/. DEV-ONLY for the same reason as lib/db.ts — Vercel's
 * filesystem won't hold this. Swap for Vercel Blob (or S3-compatible
 * storage) before deploying; app/api/blob/[id]/route.ts is the only other
 * place that needs to change.
 *
 * Each blob carries its owner alongside it (a `.owner` sidecar, same idea as
 * the existing `.type` one) so app/api/blob/[id]/route.ts can check
 * ownership directly without scanning every session to find which one
 * references a given photo id.
 */
import { promises as fs } from "fs";
import path from "path";

const BLOB_DIR = path.join(process.cwd(), "data", "blobs");

function idOf(): string {
  return (
    Date.now().toString(36) +
    Math.random().toString(36).slice(2, 10)
  );
}

export async function saveBlob(bytes: Buffer, mimeType: string, ownerId: string): Promise<string> {
  await fs.mkdir(BLOB_DIR, { recursive: true });
  const id = idOf();
  await fs.writeFile(path.join(BLOB_DIR, id), bytes);
  await fs.writeFile(path.join(BLOB_DIR, `${id}.type`), mimeType, "utf-8");
  await fs.writeFile(path.join(BLOB_DIR, `${id}.owner`), ownerId, "utf-8");
  return id;
}

export async function readBlob(
  id: string
): Promise<{ bytes: Buffer; mimeType: string; ownerId: string } | null> {
  // ids are generated by saveBlob only (base36 + random) — reject anything
  // that could look like a path segment before it ever touches fs.
  if (!/^[a-z0-9]+$/i.test(id)) return null;
  try {
    const [bytes, mimeType, ownerId] = await Promise.all([
      fs.readFile(path.join(BLOB_DIR, id)),
      fs.readFile(path.join(BLOB_DIR, `${id}.type`), "utf-8"),
      // legacy blobs saved before multi-user won't have an .owner sidecar —
      // fall back to the same "legacy" marker lib/db.ts uses for sessions.
      fs.readFile(path.join(BLOB_DIR, `${id}.owner`), "utf-8").catch(() => "legacy"),
    ]);
    return { bytes, mimeType: mimeType.trim(), ownerId: ownerId.trim() };
  } catch {
    return null;
  }
}

export async function deleteBlob(id: string): Promise<void> {
  if (!/^[a-z0-9]+$/i.test(id)) return;
  await Promise.allSettled([
    fs.unlink(path.join(BLOB_DIR, id)),
    fs.unlink(path.join(BLOB_DIR, `${id}.type`)),
    fs.unlink(path.join(BLOB_DIR, `${id}.owner`)),
  ]);
}
