/**
 * Swelleye spot slugs — harvested from swelleye.com 2026-09-16.
 * Slugs are NOT derivable from names; this table is the source of truth.
 *
 * `lat`/`lng` are needed for Open-Meteo. Wai'ao and Jialeshui are confirmed
 * (taken from their spot pages, where coordinates are embedded in the page
 * URLs). Everything else is null — fill it by opening
 * swelleye.com/en/surf-spots/<slug>/. Never approximate a coordinate; the
 * grid node it picks changes (see CLAUDE.md "Spots").
 *
 * NOTE: neighbouring spots share one Open-Meteo grid node (see CLAUDE.md,
 * "Open-Meteo's real resolution limit"). Coordinates still matter for picking
 * the right node across regions, but do not expect per-break differences.
 */
export type Region = "North" | "Northeast" | "East" | "South" | "West";

export interface Spot {
  slug: string;
  name: string;
  /** Swelleye's own Chinese name (its zh-TW spot page title), 2026-09-22. */
  nameZh: string;
  region: Region;
  lat: number | null;
  lng: number | null;
  /** From Swelleye's "Spot Infographic" — fill these in, they carry the
   *  break-specific information Open-Meteo cannot provide. */
  facing?: string;
  bestSwellDir?: string[];
  bestWindDir?: string[];
  bestTide?: string;
  /** CWA's LocationName for this spot's township, e.g. "宜蘭縣頭城鎮" —
   *  reverse-geocoded from lat/lng and cross-checked against a live CWA
   *  F-A0021-001 response (2026-09-22). Needed for lib/cwa-tide.ts; null
   *  for overseas spots (CWA is Taiwan-only) and unharvested ones. */
  tideTownship?: string;
}

export const SPOTS: Spot[] = [
  {
    slug: "shalun",
    name: "Shalun",
    nameZh: "沙崙",
    region: "North",
    // lat/lng from the `lt=`/`ln=` params embedded in the spot page's
    // surf-report/forecast/map iframe srcs (identical on the en and zh
    // pages) — see CLAUDE.md "Spots" on where Wai'ao/Jialeshui's came from.
    lat: 25.191083,
    lng: 121.413983,
    facing: "NW",
    bestSwellDir: ["N", "NW"],
    bestWindDir: ["E", "SE"],
    bestTide: "Low to Mid",
    tideTownship: "新北市淡水區",
  },
  {
    slug: "baishawan",
    name: "Baishawan",
    nameZh: "白沙灣",
    region: "North",
    lat: 25.284306,
    lng: 121.520582,
    facing: "N",
    bestSwellDir: ["N", "NNE", "NE", "ENE", "E"],
    bestWindDir: ["S", "SW"],
    bestTide: "Low to Mid",
    tideTownship: "新北市石門區",
  },
  {
    slug: "restaurants",
    name: "Restaurants",
    nameZh: "餐廳",
    region: "North",
    lat: 25.287833,
    lng: 121.5305,
    facing: "NW",
    bestSwellDir: ["N", "NE"],
    bestWindDir: ["S", "SW"],
    bestTide: "Mid to High",
    // same township as Baishawan — both sit in Shimen District
    tideTownship: "新北市石門區",
  },
  {
    slug: "jinshan",
    name: "Jinshan",
    nameZh: "金山 (中角灣)",
    region: "North",
    lat: 25.240041,
    lng: 121.633753,
    facing: "NE",
    bestSwellDir: ["N", "NNE", "NE", "E", "ESE"],
    bestWindDir: ["S", "SW"],
    bestTide: "Mid",
    tideTownship: "新北市金山區",
  },
  {
    slug: "greenbay",
    name: "Green Bay",
    nameZh: "翡翠灣",
    region: "North",
    lat: 25.188029,
    lng: 121.686354,
    facing: "NE",
    bestSwellDir: ["E", "NE"],
    bestWindDir: ["W", "SW"],
    bestTide: "Mid",
    tideTownship: "新北市萬里區",
  },
  {
    slug: "wanli",
    name: "Wanli",
    nameZh: "萬里",
    region: "North",
    lat: 25.181028,
    lng: 121.691028,
    facing: "NE",
    bestSwellDir: ["NE", "E"],
    bestWindDir: ["W", "SW"],
    bestTide: "Mid to High",
    // same township as Green Bay — both sit in Wanli District
    tideTownship: "新北市萬里區",
  },
  {
    slug: "fulong",
    name: "Fulong",
    nameZh: "福隆",
    region: "North",
    lat: 25.019898,
    lng: 121.949,
    facing: "NE",
    bestSwellDir: ["N", "NE", "E"],
    bestWindDir: ["S", "SW"],
    bestTide: "All tides",
    tideTownship: "新北市貢寮區",
  },

  {
    slug: "daxi",
    name: "Daxi",
    nameZh: "大溪",
    region: "Northeast",
    lat: 24.932601,
    lng: 121.885768,
    facing: "SE",
    bestSwellDir: ["SE", "SSE", "S", "E"],
    bestWindDir: ["NW", "W"],
    bestTide: "Mid to High",
    tideTownship: "宜蘭縣頭城鎮",
  },
  {
    slug: "gengfang",
    name: "Gengfang",
    nameZh: "梗枋",
    region: "Northeast",
    lat: 24.903032,
    lng: 121.865883,
    facing: "SE",
    bestSwellDir: ["E", "NE"],
    bestWindDir: ["NW", "W"],
    bestTide: "Mid to High",
    // same township as Daxi/Wai'ao — all sit in Toucheng Township
    tideTownship: "宜蘭縣頭城鎮",
  },
  {
    slug: "double-lions",
    name: "Double Lions",
    nameZh: "雙獅",
    region: "Northeast",
    lat: 24.888556,
    lng: 121.84961,
    facing: "E",
    bestSwellDir: ["ENE", "E", "SE", "SSE"],
    bestWindDir: ["W", "SW"],
    bestTide: "Mid to High",
    tideTownship: "宜蘭縣頭城鎮",
  },
  {
    slug: "waiao",
    name: "Wai'ao",
    nameZh: "外澳",
    region: "Northeast",
    lat: 24.882278,
    lng: 121.846166,
    facing: "E",
    bestSwellDir: ["ENE", "E", "SE", "SSE"],
    bestWindDir: ["NW", "W"],
    bestTide: "Mid to High",
    tideTownship: "宜蘭縣頭城鎮",
  },
  {
    slug: "wushi-north",
    name: "Wushi Harbor (North)",
    nameZh: "烏石港（北堤）",
    region: "Northeast",
    lat: 24.872433,
    lng: 121.842316,
    facing: "E",
    bestSwellDir: ["E", "SE", "SSE"],
    bestWindDir: ["NW", "W"],
    bestTide: "Mid",
    tideTownship: "宜蘭縣頭城鎮",
  },
  {
    slug: "wushi-south",
    name: "Wushi Harbor (South)",
    nameZh: "烏石港（南堤）",
    region: "Northeast",
    lat: 24.864329,
    lng: 121.837741,
    facing: "E",
    bestSwellDir: ["ESE", "SE", "SSE"],
    bestWindDir: ["NW", "W"],
    bestTide: "Mid",
    tideTownship: "宜蘭縣頭城鎮",
  },
  {
    slug: "choushui",
    name: "Chou Shui",
    nameZh: "臭水",
    region: "Northeast",
    lat: 24.856368,
    lng: 121.832876,
    facing: "E",
    bestSwellDir: ["ENE", "E", "ESE"],
    bestWindDir: ["WSW", "W"],
    bestTide: "Low to Mid",
    tideTownship: "宜蘭縣頭城鎮",
  },
  {
    slug: "zhuan",
    name: "Zhu'an",
    nameZh: "竹安",
    region: "Northeast",
    lat: 24.817046,
    lng: 121.821815,
    facing: "E",
    bestSwellDir: ["NE", "ENE", "E", "ESE", "SE", "SSE"],
    bestWindDir: ["WNW", "W", "WSW"],
    bestTide: "Mid to High",
    tideTownship: "宜蘭縣頭城鎮",
  },
  {
    slug: "qingshui",
    name: "Qing Shui",
    nameZh: "清水",
    region: "Northeast",
    lat: 24.6843,
    lng: 121.836799,
    facing: "E",
    bestSwellDir: ["E", "NE", "SE"],
    bestWindDir: ["W"],
    bestTide: "Mid to High",
    tideTownship: "宜蘭縣五結鄉",
  },
  {
    slug: "wuwei",
    name: "Su'ao - Wuwei Harbor",
    nameZh: "蘇澳 - 無尾港",
    region: "Northeast",
    lat: 24.610554,
    lng: 121.863855,
    facing: "NE",
    bestSwellDir: ["E", "NE"],
    bestWindDir: ["SW", "WSW"],
    bestTide: "Mid to High",
    tideTownship: "宜蘭縣蘇澳鎮",
  },

  {
    slug: "environmental-park",
    name: "Environmental Park",
    nameZh: "環保公園",
    region: "East",
    lat: 24.010331,
    lng: 121.646504,
    facing: "ENE",
    bestSwellDir: ["E", "SE"],
    bestWindDir: ["WNW", "NW"],
    bestTide: "Mid",
    tideTownship: "花蓮縣花蓮市",
  },
  {
    slug: "beibin",
    name: "Hualien Beibin",
    nameZh: "花蓮北濱",
    region: "East",
    lat: 23.976647,
    lng: 121.621122,
    facing: "SE",
    bestSwellDir: ["ESE", "SE", "S", "SSW"],
    bestWindDir: ["WNW", "NNW"],
    bestTide: "Low to Mid",
    // same township as Environmental Park — both sit in Hualien City
    tideTownship: "花蓮縣花蓮市",
  },
  {
    slug: "double-bridge",
    name: "Double Bridge",
    nameZh: "雙橋",
    region: "East",
    lat: 23.852595,
    lng: 121.59529,
    facing: "E",
    bestSwellDir: ["E", "NE", "S", "SE"],
    bestWindDir: ["W", "WNW"],
    bestTide: "Mid",
    tideTownship: "花蓮縣壽豐鄉",
  },
  {
    slug: "gongs",
    name: "Gongs",
    nameZh: "鹽寮漁港",
    region: "East",
    lat: 23.828258,
    lng: 121.584592,
    facing: "E / SE",
    bestSwellDir: ["ENE", "E", "SE"],
    bestWindDir: ["W", "WSW"],
    bestTide: "Low to Mid",
    // same township as Double Bridge — both sit in Shoufeng Township
    tideTownship: "花蓮縣壽豐鄉",
  },
  {
    slug: "jiqi",
    name: "Jiqi",
    nameZh: "磯崎",
    region: "East",
    lat: 23.708205,
    lng: 121.549359,
    facing: "E",
    bestSwellDir: ["E", "NE", "SE"],
    bestWindDir: ["W"],
    bestTide: "Mid to High",
    tideTownship: "花蓮縣豐濱鄉",
  },
  {
    slug: "eight-immortals-cave",
    name: "Baxian Dong",
    nameZh: "八仙洞",
    region: "East",
    lat: 23.397454,
    lng: 121.480661,
    facing: "E",
    bestSwellDir: ["E", "NE"],
    bestWindDir: ["W", "SW"],
    bestTide: "Mid to High",
    tideTownship: "臺東縣長濱鄉",
  },
  {
    slug: "yiwan",
    name: "Yiwan",
    nameZh: "宜灣",
    region: "East",
    lat: 23.20866,
    lng: 121.399553,
    facing: "SE",
    bestSwellDir: ["NE", "ENE", "E"],
    bestWindDir: ["W", "WSW"],
    bestTide: "Mid",
    tideTownship: "臺東縣成功鎮",
  },
  {
    slug: "chenggong",
    name: "Chenggong",
    nameZh: "成功",
    region: "East",
    lat: 23.114722,
    lng: 121.398583,
    facing: "SE",
    bestSwellDir: ["ENE", "E", "ESE"],
    bestWindDir: ["W", "WSW"],
    bestTide: "Mid to High",
    // same township as Yiwan/Duli — all sit in Chenggong Township
    tideTownship: "臺東縣成功鎮",
  },
  {
    slug: "duli",
    name: "Duli",
    nameZh: "都歷",
    region: "East",
    lat: 23.022447,
    lng: 121.334657,
    facing: "E",
    bestSwellDir: ["E", "NE", "ESE"],
    bestWindDir: ["W", "WSW"],
    bestTide: "Mid",
    tideTownship: "臺東縣成功鎮",
  },
  {
    slug: "donghe",
    name: "Donghe",
    nameZh: "東河",
    region: "East",
    lat: 22.973653,
    lng: 121.311941,
    facing: "E",
    bestSwellDir: ["E", "NE", "SE", "SSE"],
    bestWindDir: ["W", "SW"],
    bestTide: "Mid",
    tideTownship: "臺東縣東河鄉",
  },
  {
    slug: "jinzun",
    name: "Jinzun",
    nameZh: "金樽",
    region: "East",
    lat: 22.955439,
    lng: 121.295982,
    facing: "SE",
    bestSwellDir: ["E", "NE", "S", "SE"],
    bestWindDir: ["NW", "W"],
    bestTide: "Mid",
    // same township as Donghe — both sit in Donghe Township
    tideTownship: "臺東縣東河鄉",
  },
  {
    slug: "dulan",
    name: "Dulan",
    nameZh: "都蘭",
    region: "East",
    lat: 22.880944,
    lng: 121.241778,
    facing: "SE",
    bestSwellDir: ["ENE", "E", "SE", "SSE"],
    bestWindDir: ["W", "WNW"],
    bestTide: "Mid to High",
    // same township as Donghe/Jinzun — all sit in Donghe Township
    tideTownship: "臺東縣東河鄉",
  },
  {
    slug: "taitung",
    name: "Taitung",
    nameZh: "台東",
    region: "East",
    lat: 22.737194,
    lng: 121.145832,
    // infographic on the spot page returns "N/A" for every field here —
    // a general area page, not a tuned break. Coordinate is real (matches
    // the en and zh pages), so left in; no facing/bestSwellDir/bestWindDir/
    // bestTide to report.
    tideTownship: "臺東縣臺東市",
  },

  {
    slug: "jiupeng",
    name: "Jiupeng",
    nameZh: "九棚",
    region: "South",
    lat: 22.109309,
    lng: 120.891043,
    facing: "NE",
    bestSwellDir: ["E", "ESE", "SE"],
    bestWindDir: ["NW", "W"],
    bestTide: "Mid",
    // same township as Jialeshui — both sit in Manzhou Township
    tideTownship: "屏東縣滿州鄉",
  },
  {
    slug: "jialeshui",
    name: "Jialeshui",
    nameZh: "佳樂水",
    region: "South",
    // confirmed from the spot page — supersedes an earlier ~10km-off guess
    // of 22.05, 120.9 (see CLAUDE.md "Spots")
    lat: 21.987722,
    lng: 120.845982,
    facing: "SE",
    bestSwellDir: ["ENE", "E", "SE", "SSE"],
    bestWindDir: ["W"],
    bestTide: "Mid",
    tideTownship: "屏東縣滿州鄉",
  },
  {
    slug: "nanwan",
    name: "Nanwan",
    nameZh: "南灣",
    region: "South",
    // CLAUDE.md documents this as confirmed from the spot page, but it had
    // never actually landed in this file (still null/null) — filled in now
    // while wiring up tideTownship, since tide needs real coordinates too.
    lat: 21.959292,
    lng: 120.762598,
    facing: "S",
    bestSwellDir: ["S", "SE", "SSW"],
    bestWindDir: ["N", "NE"],
    bestTide: "Low to Mid",
    tideTownship: "屏東縣恆春鎮",
  },
  {
    slug: "sheliao",
    name: "Sheliao",
    nameZh: "射寮",
    region: "South",
    lat: 22.056413,
    lng: 120.703433,
    facing: "W",
    bestSwellDir: ["W", "SW"],
    bestWindDir: ["E"],
    bestTide: "Mid to Low",
    tideTownship: "屏東縣車城鄉",
  },

  {
    slug: "qijin",
    name: "Qijin",
    nameZh: "旗津",
    region: "West",
    lat: 22.604148,
    lng: 120.270907,
    facing: "SW",
    bestSwellDir: ["S", "SW"],
    bestWindDir: ["N", "NE"],
    bestTide: "Low to Mid",
    tideTownship: "高雄市旗津區",
  },
  {
    slug: "yuguangdao",
    name: "Yuguangdao",
    nameZh: "漁光島 (馬場)",
    region: "West",
    lat: 22.980676,
    lng: 120.154545,
    facing: "SW",
    bestSwellDir: ["S", "SW"],
    bestWindDir: ["E", "NE"],
    bestTide: "All tides",
    tideTownship: "臺南市安平區",
  },
  {
    slug: "sicao-bridge",
    name: "Sicao Bridge",
    nameZh: "四草橋",
    region: "West",
    lat: 22.993381,
    lng: 120.141996,
    facing: "SW",
    bestSwellDir: ["S", "SW"],
    bestWindDir: ["N", "NE"],
    bestTide: "All tides",
    tideTownship: "臺南市安南區",
  },
  {
    slug: "shanshui",
    name: "Shanshui",
    nameZh: "山水",
    region: "West",
    // Penghu, not the Taiwan mainland — see report. CWA F-A0021-001 does
    // carry a 澎湖縣馬公市 entry, confirmed live, so tide still works.
    lat: 23.513,
    lng: 119.59075,
    facing: "S",
    bestSwellDir: ["S", "SE", "SW"],
    bestWindDir: ["N", "NW"],
    bestTide: "All tides",
    tideTownship: "澎湖縣馬公市",
  },
  {
    slug: "songbai",
    name: "Songbai Harbor",
    nameZh: "松柏港",
    region: "West",
    lat: 24.432481,
    lng: 120.616827,
    facing: "NW",
    bestSwellDir: ["N", "NW"],
    bestWindDir: ["E", "SE"],
    bestTide: "Mid to High",
    tideTownship: "臺中市大甲區",
  },
  {
    slug: "waipu",
    name: "Waipu Fishing Harbor",
    nameZh: "外埔北堤",
    region: "West",
    lat: 24.653837,
    lng: 120.773386,
    facing: "NW",
    bestSwellDir: ["N", "NW"],
    bestWindDir: ["SE", "SSE"],
    bestTide: "Mid",
    tideTownship: "苗栗縣後龍鎮",
  },
  {
    slug: "zhunan",
    name: "Zhunan",
    nameZh: "竹南",
    region: "West",
    lat: 24.697639,
    lng: 120.854471,
    facing: "NW",
    bestSwellDir: ["N", "NW", "W"],
    bestWindDir: ["E", "SE"],
    bestTide: "Mid",
    tideTownship: "苗栗縣竹南鎮",
  },
];

export const spotBySlug = (slug: string) => SPOTS.find((s) => s.slug === slug);
